### PR TITLE
Webservice Beta component pull request

### PR DESCRIPTION
**Pull request by whatfield73**
I added files to add the webservice component to the gallery

### CODE REVIEW

**Comment by unwiredben** [comment]
If you still want to submit this, we'd appreciate you namespacing the WebService kind so it won't conflict with the new enyo.WebService kind that's coming in the next release.

**Comment by unwiredben** [comment]
also, a cleaner diff would be really useful for verifying the pull, and you didn't update the index.html to add the kind to the noscript list.

**Comment by whatfield73** [comment]
Sure,

I'm not sure if others will want it or not.  Do you think they will?  It is easier to port from Enyo 1 than the new WebService kind.  If I do what would be a good name?

Will

-----Original Message-----

**Comment by unwiredben** [comment]
Classic.WebService, maybe?

**Comment by whatfield73** [comment]
Ok,  I'm not sure what you mean by "cleaner diff"

**Comment by unwiredben** [comment]
I mean use "git rebase" to rebase your commit to the top of the trunk and move it into just a single commit to change the gallery repo.  That makes it a lot easier for us to review.

**Comment by whatfield73** [comment]
Ok,

All done.  Should I submit a new request?

**Pull request closed without merging**
