### PR TITLE
File Input Decorator image

### PR DESCRIPTION
**Pull request by JMTK**

### CODE REVIEW

**Comment by unwiredben** [comment]
I can't take the image without the other changes needed to add this to the gallery.  Can you add those to your fork?  The pull request should be updated.

**Comment by JMTK** [comment]
https://github.com/enyojs/gallery/pull/50

Sorry about that, I swore I pushed it.

**Comment by JMTK** [comment]
Sorry I don't know what happened in the gallery_manifest.json, in the commit where it says I changed every single line.. the https://github.com/enyojs/gallery/pull/50 one is the correct one I believe...

**Comment by unwiredben** [comment]
Closing to have you resubmit as one request.

**Pull request closed without merging**
